### PR TITLE
SSB: Add grimAuxiliatrix

### PR DESCRIPTION
**Pull request by Volco**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Conflicts

**Comment by Volco** [comment]
rip, seems it was caused by the false update and would mess up the alphabetical order if we use both

**Comment by ghost** [comment]
Do what I do and fix the conflicts on here

**Comment by Volco** [comment]
I just need time is all lol

**Comment by HoeenCoder** [comment]
Oh uh i didnt see you took this sorry, I was working with @TheTiksiBranch on this instead and pushed the change.

**Comment by Volco** [comment]
ok

**Pull request closed without merging**
