### PR TITLE
Add Zarel

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by Spandamn** [comment]
Tested
works well

**Comment by ghost** [comment]
Ok so, the formchanging and spa boost should be after the move hits, not before. Like how the original move relic song goes.

**Comment by Spandamn** [comment]
> regardless of the outcome of the move. 
Which event to use, onAfterMoveSecondarySelf right?

**Comment by Spandamn** [comment]
looks good?

**Pull request merged**
